"""expand marketplace domain

Revision ID: 4377a23a9714
Revises: f01e150de3ea
Create Date: 2026-06-19 11:43:24.741997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4377a23a9714'
down_revision: Union[str, Sequence[str], None] = 'f01e150de3ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    listing_condition = sa.Enum(
        "NEW",
        "LIKE_NEW",
        "GOOD",
        "FAIR",
        "POOR",
        name="listingcondition"
    )

    listing_status = sa.Enum(
        "ACTIVE",
        "RESERVED",
        "SOLD",
        "REMOVED",
        name="listingstatus"
    )

    user_role = sa.Enum(
        "USER",
        "ADMIN",
        name="userrole"
    )

    listing_condition.create(op.get_bind())
    listing_status.create(op.get_bind())
    user_role.create(op.get_bind())
    
    op.create_table('campuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('hostels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.add_column('listing_images', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('listing_images', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('listings', sa.Column('condition', sa.Enum('NEW', 'LIKE_NEW', 'GOOD', 'FAIR', 'POOR', name='listingcondition'), nullable=False))
    op.add_column('listings', sa.Column('status', sa.Enum('ACTIVE', 'RESERVED', 'SOLD', 'REMOVED', name='listingstatus'), nullable=False))
    op.add_column('listings', sa.Column('category_id', sa.UUID(), nullable=False))
    op.create_foreign_key("fk_listings_category_id", 'listings', 'categories', ['category_id'], ['id'])
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False))
    op.add_column('users', sa.Column('campus_id', sa.UUID(), nullable=False))
    op.add_column('users', sa.Column('hostel_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_foreign_key("fk_users_campus_id", 'users', 'campuses', ['campus_id'], ['id'])
    op.create_foreign_key("fk_users_hostel_id", 'users', 'hostels', ['hostel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'hostel_id')
    op.drop_column('users', 'campus_id')
    op.drop_column('users', 'role')
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.drop_column('listings', 'category_id')
    op.drop_column('listings', 'status')
    op.drop_column('listings', 'condition')
    op.drop_column('listing_images', 'updated_at')
    op.drop_column('listing_images', 'created_at')
    op.drop_table('hostels')
    op.drop_table('categories')
    op.drop_table('campuses')

    sa.Enum(name="listingcondition").drop(
        op.get_bind(),
        checkfirst=True
    )

    sa.Enum(name="listingstatus").drop(
        op.get_bind(),
        checkfirst=True
    )

    sa.Enum(name="userrole").drop(
        op.get_bind(),
        checkfirst=True
    )
    # ### end Alembic commands ###
