"""fix hostel constraints

Revision ID: 87f58508beb3
Revises: 4377a23a9714
Create Date: 2026-06-19 13:08:53.560045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f58508beb3'
down_revision: Union[str, Sequence[str], None] = '4377a23a9714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('hostels_name_key'), 'hostels', type_='unique')
    op.drop_constraint(op.f('hostels_slug_key'), 'hostels', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('hostels_slug_key'), 'hostels', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('hostels_name_key'), 'hostels', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
