"""added tokenid for ref. token

Revision ID: e80ad57568fb
Revises: dcc0073f6537
Create Date: 2026-07-08 14:22:34.263843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e80ad57568fb'
down_revision: Union[str, Sequence[str], None] = 'dcc0073f6537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_refresh_tokens_token_id'), 'refresh_tokens', ['token_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_token_id'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'token_id')
    # ### end Alembic commands ###
